// variable name definitions as used in mceep
// defined in var_dat.cmn include file
 // global array of variable names 
TString var[160]; 

Int_t init_var()
{
var[1].Append("BEAM_E1 ");
var[2].Append("TH_E_I  ");
var[3].Append("BEAM_E2 ");
var[4].Append("PH_E_I  ");
var[5].Append("BEAM_E3 ");
var[6].Append("PF_E_I  ");
var[7].Append("BEAM_P1 ");
var[8].Append("TH_P_I  ");
var[9].Append("BEAM_P2 ");
var[10].Append("PH_P_I  ");
var[11].Append("BEAM_P3 ");
var[12].Append("PF_P_I  ");
var[13].Append("E0_I    ");
var[14].Append("TSCAT   ");
var[15].Append("OMEGA   ");
var[16].Append("QMAG    ");
var[17].Append("THEQ    ");
var[18].Append("PHIQ    ");
var[19].Append("QMU2    ");
var[20].Append("X       ");
var[21].Append("EPSILON ");
var[22].Append("THETA_PQ");
var[23].Append("PHI_X   ");
var[24].Append("MISS_M  ");
var[25].Append("PREC    ");
var[26].Append("PRMAG   ");
var[27].Append("RECFAC  ");
var[28].Append("W       ");
var[29].Append("THETA_CM");
var[30].Append("TOF_REL ");
var[31].Append("THET_PRQ");
var[32].Append("SURVIVAL");
var[33].Append("BETA_H  ");
var[34].Append("EMISS   ");
var[35].Append("MMSQ    ");
var[36].Append("PREC_X  ");
var[37].Append("PREC_Y  ");
var[38].Append("PREC_Z  ");
var[39].Append("ELOSS_B ");
var[40].Append("ELOSS_E ");
var[41].Append("ELOSS_P ");
var[42].Append("DE_DX_B ");
var[43].Append("DE_DX_E ");
var[44].Append("DE_DX_P ");
var[45].Append("VERTEX_X");
var[46].Append("VERTEX_Y");
var[47].Append("VERTEX_Z");
var[48].Append("PREC_TH ");
var[49].Append("PREC_PH ");
var[51].Append("Snn     ");
var[52].Append("Snt     ");
var[53].Append("Snl     ");
var[54].Append("Stn     ");
var[55].Append("Stt     ");
var[56].Append("Stl     ");
var[57].Append("Sln     ");
var[58].Append("Slt     ");
var[59].Append("Sll     ");
var[61].Append("X_E_TG  ");
var[62].Append("TH_E_TG ");
var[63].Append("Y_E_TG  ");
var[64].Append("PH_E_TG ");
var[65].Append("L_E_TG  ");
var[66].Append("DP_E_TG ");
var[71].Append("X_P_TG  ");
var[72].Append("TH_P_TG ");
var[73].Append("Y_P_TG  ");
var[74].Append("PH_P_TG ");
var[75].Append("L_P_TG  ");
var[76].Append("DP_P_TG ");
var[81].Append("X_E_FP  ");
var[82].Append("TH_E_FP ");
var[83].Append("Y_E_FP  ");
var[84].Append("PH_E_FP ");
var[85].Append("L_E_FP  ");
var[86].Append("DP_E_FP ");
var[91].Append("X_P_FP  ");
var[92].Append("TH_P_FP ");
var[93].Append("Y_P_FP  ");
var[94].Append("PH_P_FP ");
var[95].Append("L_P_FP  ");
var[96].Append("DP_P_FP ");
var[101].Append("X_E_FIN ");
var[102].Append("TH_E_FIN");
var[103].Append("Y_E_FIN ");
var[104].Append("PH_E_FIN");
var[105].Append("L_E_FIN ");
var[106].Append("DP_E_FIN");
var[111].Append("X_P_FIN ");
var[112].Append("TH_P_FIN");
var[113].Append("Y_P_FIN ");
var[114].Append("PH_P_FIN");
var[115].Append("L_P_FIN ");
var[116].Append("DP_P_FIN");
var[117].Append("E0_V    ");
var[118].Append("EF_V    ");
var[119].Append("OMEGA_V ");
var[120].Append("QMAG_V  ");
var[121].Append("QMU2_V  ");
var[122].Append("PHIX_V  ");
var[123].Append("EMISS_V ");
var[124].Append("MISSM_V ");
var[125].Append("PRMAG_V ");
var[126].Append("W_V     ");
var[127].Append("THCM_V  ");
var[128].Append("THPQ_V  ");
var[129].Append("TSCAT_V ");
var[130].Append("EQ1_2_X");
var[131].Append("EQ1_2_Y");
var[132].Append("EDIP_1_X");
var[133].Append("EDIP_1_Y");
var[134].Append("EDIP_2_X");
var[135].Append("EDIP_2_Y");
var[136].Append("EQ3_1_X ");
var[137].Append("EQ3_1_Y ");
var[138].Append("EQ3_2_X ");
var[139].Append("EQ3_2_Y ");
var[140].Append("PQ1_2_X");
var[141].Append("PQ1_2_Y");
var[142].Append("PDIP_1_X");
var[143].Append("PDIP_1_Y");
var[144].Append("PDIP_2_X");
var[145].Append("PDIP_2_Y");
var[146].Append("PQ3_1_X ");
var[147].Append("PQ3_1_Y ");
var[148].Append("PQ3_2_X ");
var[149].Append("PQ3_2_Y ");
var[150].Append("E_RFN   ");
var[151].Append("P_RFN   ");
var[152].Append("MAG1_1_X");
var[153].Append("MAG1_1_Y");
var[154].Append("MAG1_2_X");
var[155].Append("MAG1_2_Y");
var[156].Append("MAG2_1_X");
var[157].Append("MAG2_1_Y");
var[158].Append("MAG2_2_X");
var[159].Append("MAG2_2_Y");
return(0);
}
